# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # make vm db1
    config.vm.define "db1" do |node|
      node.vm.box = "centos/7"
      node.vm.provider "virtualbox" do |vb|        # Máy ảo dùng nền tảng virtualbox, với các cấu hình bổ sung thêm cho provider
        vb.name = "db1"                 # đặt tên máy ảo tạo ra
        vb.cpus = 2                                # cấp 2 nhân CPU
        vb.memory = "2048"                         # cấu hình dùng 2GB bộ nhớ
      end
      node.vm.hostname = "db1"
      node.vm.network "public_network", ip: "172.20.10.225"
      node.vm.provision "shell", path: "setup-db1.sh"
    end

    # make vm db2
    config.vm.define "db2" do |node|
      node.vm.box = "centos/7"
      node.vm.provider "virtualbox" do |vb|        # Máy ảo dùng nền tảng virtualbox, với các cấu hình bổ sung thêm cho provider
        vb.name = "db2"                            # đặt tên máy ảo tạo ra
        vb.cpus = 2                                # cấp 2 nhân CPU
        vb.memory = "2048"                         # cấu hình dùng 2GB bộ nhớ
      end
      node.vm.hostname = "db2"
      node.vm.network "public_network", ip: "172.20.10.226"
      node.vm.provision "shell", path: "setup-db2.sh"   
    end

    # make vm 
    config.vm.define "db3" do |node|
      node.vm.box = "centos/7"
      node.vm.provider "virtualbox" do |vb|        # Máy ảo dùng nền tảng virtualbox, với các cấu hình bổ sung thêm cho provider
        vb.name = "db3"                            # đặt tên máy ảo tạo ra
        vb.cpus = 2                                # cấp 2 nhân CPU
        vb.memory = "2048"                         # cấu hình dùng 2GB bộ nhớ
      end
      node.vm.hostname = "db3"
      node.vm.network "public_network", ip: "172.20.10.227"
      node.vm.provision "shell", path: "setup-db3.sh"   
    end

    # make vm db4
    config.vm.define "db4" do |node|
      node.vm.box = "centos/7"
      node.vm.provider "virtualbox" do |vb|        # Máy ảo dùng nền tảng virtualbox, với các cấu hình bổ sung thêm cho provider
        vb.name = "db4"                            # đặt tên máy ảo tạo ra
        vb.cpus = 2                                # cấp 2 nhân CPU
        vb.memory = "2048"                         # cấu hình dùng 2GB bộ nhớ
      end
      node.vm.hostname = "db4"
      node.vm.network "public_network", ip: "172.20.10.228"
      node.vm.provision "shell", path: "setup-db4.sh"   
    end

    # make vm 
    config.vm.define "db5" do |node|
      node.vm.box = "centos/7"
      node.vm.provider "virtualbox" do |vb|        # Máy ảo dùng nền tảng virtualbox, với các cấu hình bổ sung thêm cho provider
        vb.name = "db5"                            # đặt tên máy ảo tạo ra
        vb.cpus = 2                                # cấp 2 nhân CPU
        vb.memory = "2048"                         # cấu hình dùng 2GB bộ nhớ
      end
      node.vm.hostname = "db5"
      node.vm.network "public_network", ip: "172.20.10.229"
      node.vm.provision "shell", path: "setup-db5.sh"   
    end
    
  end